# This file was generated by the {rix} R package v0.17.2 on 2025-12-09
# with following call:
# >rix(r_ver = "4.5.2",
#  > r_pkgs = all_pkgs,
#  > system_pkgs = c("awscli2",
#  > "bc",
#  > "btop",
#  > "cacert",
#  > "clang",
#  > "cmdstan",
#  > "curlMinimal",
#  > "direnv",
#  > "duckdb",
#  > "gcc",
#  > "gettext",
#  > "gh",
#  > "git",
#  > "glibcLocales",
#  > "gnupg",
#  > "htop",
#  > "jq",
#  > "less",
#  > "libgcc",
#  > "libiconv",
#  > "locale",
#  > "nano",
#  > "nix",
#  > "nodejs",
#  > "ollama",
#  > "pandoc",
#  > "positron-bin",
#  > "quarto",
#  > "R",
#  > "texliveBasic",
#  > "toybox",
#  > "tree",
#  > "typst",
#  > "unzip",
#  > "which"),
#  > git_pkgs = git_pkgs_list,
#  > ide = "positron",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = "\nmkdir -p $HOME/.config/positron\nNIX_SHELL_PATH=$(readlink /Users/johngavin/docs_gh/rix.setup/nix-shell-root)\nif [ -z \"$NIX_SHELL_PATH\" ]; then NIX_SHELL_PATH=\"$out\"; fi\n\ncat > $HOME/.config/positron/nix-terminal-wrapper.sh <<EOF\n#!/bin/bash\nprintf \"%s\n\" \"Activating Nix shell environment...\"\ntrue && source $NIX_SHELL_PATH/etc/profile.d/nix-shell.sh\n\nif declare -f __start_nix_shell_environment > /dev/null; then\n    __start_nix_shell_environment\nfi\n\nprintf \"%s\n\" \"Nix environment fully sourced.\"\n\necho \"set -o emacs\" > ~/.nix-shell-bashrc\necho \"bind \"\\e[A\": history-search-backward\"\" >> ~/.nix-shell-bashrc\necho \"bind \"\\e[B\": history-search-forward\"\" >> ~/.nix-shell-bashrc\nif [ -f ~/.bashrc ]; then source ~/.bashrc; fi\n\nexec /usr/bin/env bash --rcfile ~/.nix-shell-bashrc -i\nEOF\n\nchmod +x $HOME/.config/positron/nix-terminal-wrapper.sh\nexport RSTUDIO_TERM_EXEC=$HOME/.config/positron/nix-terminal-wrapper.sh\nexport R_MAKEVARS_USER=/dev/null\nunset CI\nprintf \"Setup complete\n\"\n")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-12-08.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      ahead
      devtools
      dplyr
      esgtoolkit
      forecast
      gert
      ggplot2
      gh
      knitr
      quarto
      rix
      rmarkdown
      tarchetypes
      targets
      testthat
      usethis;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      awscli2
      bc
      btop
      cacert
      clang
      cmdstan
      curlMinimal
      direnv
      duckdb
      gcc
      gettext
      gh
      git
      glibcLocales
      gnupg
      htop
      jq
      less
      libgcc
      libiconv
      locale
      nano
      nix
      nodejs
      ollama
      pandoc
      positron-bin
      quarto
      R
      texliveBasic
      toybox
      tree
      typst
      unzip
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    shellHook = "
mkdir -p $HOME/.config/positron
NIX_SHELL_PATH=$(readlink /Users/johngavin/docs_gh/rix.setup/nix-shell-root)
if [ -z "$NIX_SHELL_PATH" ]; then NIX_SHELL_PATH="$out"; fi

cat > $HOME/.config/positron/nix-terminal-wrapper.sh <<EOF
#!/bin/bash
printf "%s
" "Activating Nix shell environment..."
true && source $NIX_SHELL_PATH/etc/profile.d/nix-shell.sh

if declare -f __start_nix_shell_environment > /dev/null; then
    __start_nix_shell_environment
fi

printf "%s
" "Nix environment fully sourced."

echo "set -o emacs" > ~/.nix-shell-bashrc
echo "bind "\e[A": history-search-backward"" >> ~/.nix-shell-bashrc
echo "bind "\e[B": history-search-forward"" >> ~/.nix-shell-bashrc
if [ -f ~/.bashrc ]; then source ~/.bashrc; fi

exec /usr/bin/env bash --rcfile ~/.nix-shell-bashrc -i
EOF

chmod +x $HOME/.config/positron/nix-terminal-wrapper.sh
export RSTUDIO_TERM_EXEC=$HOME/.config/positron/nix-terminal-wrapper.sh
export R_MAKEVARS_USER=/dev/null
unset CI
printf "Setup complete
"
";
  }; 
in
  {
    inherit pkgs shell;
  }
