# This file was generated by the {rix} R package v0.17.2 on 2025-12-12
# with following call:
# >rix::rix(r_ver = "1482d00f8f658fd443526febba6c9fd9754cb356",
#  > r_pkgs = r_pkgs_all,
#  > system_pkgs = sys_pkgs,
#  > git_pkgs = rix_git_pkgs,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = FALSE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/1482d00f8f658fd443526febba6c9fd9754cb356.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      devtools
      dplyr
      forecast
      fpp
      gert
      ggplot2
      gh
      knitr
      quarto
      rcmdcheck
      rmarkdown
      roxygen2
      tarchetypes
      targets
      testthat
      usethis;
  };
 
    ForecastComb = (pkgs.rPackages.buildRPackage {
      name = "ForecastComb";
      src = pkgs.fetchgit {
        url = "https://github.com/thierrymoudiki/ForecastComb";
        rev = "3e80024067fde690d168f8ce756abec71e58161b";
        sha256 = "sha256-NpnhxDRw385lj/YM+GdKabYCkHu4kxYr2uQ3l2LIGgM=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          remotes
          glmnet
          ahead
          forecast
          ggplot2
          Matrix
          mtsdi
          psych
          quadprog
          quantreg;
      };
    });

    misc = (pkgs.rPackages.buildRPackage {
      name = "misc";
      src = pkgs.fetchgit {
        url = "https://github.com/thierrymoudiki/misc";
        rev = "541dbcd33c7b86525c450638b8e66ea48c20a7da";
        sha256 = "sha256-2lRKY8Zy/y0viDpT1iZB6QHZatzF61+vg/SlL1tO/n8=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          MASS
          foreach
          doSNOW
          snow;
      };
    });

    ahead = (pkgs.rPackages.buildRPackage {
      name = "ahead";
      src = pkgs.fetchgit {
        url = "https://github.com/Techtonique/ahead";
        rev = "290c76194890faa629de57a29e17a2dce95a9cbe";
        sha256 = "sha256-varLbi6rK6FJIVbnu2fba8IJX9TeQb2Dbc0l7uwhx/0=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          Rcpp
          foreach
          snow
          forecast
          ggplot2
          tseries
          randtoolbox;
      } ++ [ misc ForecastComb ];
    });

    esgtoolkit = (pkgs.rPackages.buildRPackage {
      name = "esgtoolkit";
      src = pkgs.fetchgit {
        url = "https://github.com/Techtonique/esgtoolkit";
        rev = "0a9ad8ed1d52de4a66a997dc48e930aa49560a2b";
        sha256 = "sha256-8gMAPQpvHZA0FT7HHJAO3iKkoBamTGHXbqW3JMA5EZI=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          ggplot2
          gridExtra
          reshape2
          VineCopula
          randtoolbox
          zoo
          data_table
          Rcpp;
      } ++ [ misc ];
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      curlMinimal
      gh
      git
      glibcLocales
      nix
      pandoc
      quarto
      R
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ esgtoolkit ahead rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
