# This file was generated by the {rix} R package v0.17.2 on 2025-12-11
# with following call:
# >rix(r_ver = "4.4.2",
#  > r_pkgs = r_pkgs,
#  > system_pkgs = sys_pkgs,
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = shell_hook)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-02-24.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      ahead
      devtools
      dplyr
      esgtoolkit
      forecast
      gert
      ggplot2
      gh
      knitr
      quarto
      rcmdcheck
      rix
      rmarkdown
      roxygen2
      tarchetypes
      targets
      testthat
      usethis;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      awscli2
      bc
      btop
      cacert
      clang
      curlMinimal
      direnv
      duckdb
      gcc
      gh
      git
      glibcLocales
      gnupg
      htop
      jq
      less
      nix
      nodejs
      pandoc
      quarto
      R
      tree
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    shellHook = "
mkdir -p $HOME/.config/positron
mkdir -p $HOME/.R/library
echo "R_LIBS_USER=$HOME/.R/library" >> $HOME/.Renviron

# Optional: Setup Positron/RStudio wrapper if needed (simplified from existing default.nix)
export R_MAKEVARS_USER=/dev/null
unset CI
printf "Environment loaded.\n"
";
  }; 
in
  {
    inherit pkgs shell;
  }
