# This file was generated by the {rix} R package v0.17.2 on 2025-12-09
# with following call:
# >rix(date = "2025-11-03",
#  > r_pkgs = r_pkgs,
#  > system_pkgs = system_pkgs,
#  > git_pkgs = git_pkgs_list,
#  > ide = "positron",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = shell_hook,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-11-03.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      devtools
      dplyr
      forecast
      ggplot2
      knitr
      pkgdown
      quarto
      rix
      rmarkdown
      tarchetypes
      targets
      testthat
      usethis;
  };
 

    ahead = (pkgs.rPackages.buildRPackage {
      name = "ahead";
    postPatch = "rm -f src/*.o src/*.so src/*.dll";
      src = pkgs.fetchgit {
        url = "https://github.com/Techtonique/ahead";
        rev = "290c76194890faa629de57a29e17a2dce95a9cbe";
        sha256 = "sha256-varLbi6rK6FJIVbnu2fba8IJX9TeQb2Dbc0l7uwhx/0=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          Rcpp
          foreach
          snow
          forecast
          ggplot2
          tseries
          randtoolbox;
      } ++ [ misc  ];
    });

    esgtoolkit = (pkgs.rPackages.buildRPackage {
      name = "esgtoolkit";
    postPatch = "rm -f src/*.o src/*.so src/*.dll";
      src = pkgs.fetchgit {
        url = "https://github.com/Techtonique/esgtoolkit";
        rev = "0a9ad8ed1d52de4a66a997dc48e930aa49560a2b";
        sha256 = "sha256-8gMAPQpvHZA0FT7HHJAO3iKkoBamTGHXbqW3JMA5EZI=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          ggplot2
          gridExtra
          reshape2
          VineCopula
          randtoolbox
          zoo
          data_table
          Rcpp;
      } ++ [ misc ];
    });

    misc = (pkgs.rPackages.buildRPackage {
      name = "misc";
    postPatch = "rm -f src/*.o src/*.so src/*.dll";
      src = pkgs.fetchgit {
        url = "https://github.com/thierrymoudiki/misc";
        rev = "6327354f0d4cce895031e59421ceb5fafed4c1a7";
        sha256 = "sha256-/Xn5BU17c8HfTjnl70DrRzRv3lJopUK0So2HwL2VbIQ=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          MASS
          foreach
          doSNOW
          snow;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      awscli2
      bc
      btop
      cacert
      clang
      cmdstan
      curlMinimal
      direnv
      duckdb
      gcc
      gettext
      gh
      git
      glibcLocales
      gnupg
      htop
      jq
      less
      libgcc
      libiconv
      locale
      nano
      nix
      nodejs
      ollama
      pandoc
      positron-bin
      quarto
      R
      texliveBasic
      toybox
      tree
      typst
      unzip
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ misc esgtoolkit ahead rpkgs system_packages ];
    shellHook = "
mkdir -p $HOME/.config/positron
NIX_SHELL_PATH=$(readlink /Users/johngavin/docs_gh/rix.setup/nix-shell-root)
if [ -z \"$NIX_SHELL_PATH\" ]; then NIX_SHELL_PATH=\"$out\"; fi

cat > $HOME/.config/positron/nix-terminal-wrapper.sh <<EOF
#!/bin/bash
printf \"%s\\n\" \"Activating Nix shell environment...\"
true && source $NIX_SHELL_PATH/etc/profile.d/nix-shell.sh

if declare -f __start_nix_shell_environment > /dev/null; then
    __start_nix_shell_environment
fi

printf \"%s\\n\" \"Nix environment fully sourced.\"

echo \"set -o emacs\" > ~/.nix-shell-bashrc
echo \"bind \\\"\\\\e[A\\\": history-search-backward\\\"\" >> ~/.nix-shell-bashrc
echo \"bind \\\"\\\\e[B\\\": history-search-forward\\\"\" >> ~/.nix-shell-bashrc
if [ -f ~/.bashrc ]; then source ~/.bashrc; fi

exec /usr/bin/env bash --rcfile ~/.nix-shell-bashrc -i
EOF

chmod +x $HOME/.config/positron/nix-terminal-wrapper.sh
export RSTUDIO_TERM_EXEC=$HOME/.config/positron/nix-terminal-wrapper.sh
export R_MAKEVARS_USER=/dev/null
unset CI
printf \"Setup complete\\n\"
";
  }; 
in
  {
    inherit pkgs shell;
  }
