# This file is automatically generated by R/setup/maintain_env.R
# Do not edit this file directly.

r_pkgs <- c(
  "ahead",
  "devtools",
  "dplyr",
  "esgtoolkit",
  "forecast",
  "gert",
  "ggplot2",
  "gh",
  "knitr",
  "quarto",
  "rcmdcheck",
  "rix",
  "rmarkdown",
  "roxygen2",
  "tarchetypes",
  "targets",
  "testthat",
  "usethis"
)
