# package.nix - Builds rArimaOption R package as a Nix derivation from local source
# Generated by: R/setup/generate_nix_files.R

{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/1482d00f8f658fd443526febba6c9fd9754cb356.tar.gz") {} 
}:

let
misc = (pkgs.rPackages.buildRPackage {
  name = "misc";
  src = pkgs.fetchgit {
    url = "https://github.com/thierrymoudiki/misc";
    rev = "541dbcd33c7b86525c450638b8e66ea48c20a7da";
    sha256 = "sha256-2lRKY8Zy/y0viDpT1iZB6QHZatzF61+vg/SlL1tO/n8=";
  };
  
  
  propagatedBuildInputs = [
    pkgs.rPackages.MASS
      pkgs.rPackages.foreach
      pkgs.rPackages.doSNOW
      pkgs.rPackages.snow
  ];
});
ForecastComb = (pkgs.rPackages.buildRPackage {
  name = "ForecastComb";
  src = pkgs.fetchgit {
    url = "https://github.com/thierrymoudiki/ForecastComb";
    rev = "3e80024067fde690d168f8ce756abec71e58161b";
    sha256 = "sha256-NpnhxDRw385lj/YM+GdKabYCkHu4kxYr2uQ3l2LIGgM=";
  };
  postPatch = "sed -i 's/ahead//g' DESCRIPTION";
  
  propagatedBuildInputs = [
    pkgs.rPackages.remotes
      pkgs.rPackages.glmnet
      pkgs.rPackages.forecast
      pkgs.rPackages.ggplot2
      pkgs.rPackages.Matrix
      pkgs.rPackages.mtsdi
      pkgs.rPackages.psych
      pkgs.rPackages.quadprog
      pkgs.rPackages.quantreg
      misc
  ];
});
esgtoolkit = (pkgs.rPackages.buildRPackage {
  name = "esgtoolkit";
  src = pkgs.fetchgit {
    url = "https://github.com/Techtonique/esgtoolkit";
    rev = "0a9ad8ed1d52de4a66a997dc48e930aa49560a2b";
    sha256 = "sha256-8gMAPQpvHZA0FT7HHJAO3iKkoBamTGHXbqW3JMA5EZI=";
  };
  
  
  propagatedBuildInputs = [
    pkgs.rPackages.ggplot2
      pkgs.rPackages.gridExtra
      pkgs.rPackages.reshape2
      pkgs.rPackages.VineCopula
      pkgs.rPackages.randtoolbox
      pkgs.rPackages.zoo
      pkgs.rPackages.data_table
      pkgs.rPackages.Rcpp
      misc
  ];
});
ahead = (pkgs.rPackages.buildRPackage {
  name = "ahead";
  src = pkgs.fetchgit {
    url = "https://github.com/Techtonique/ahead";
    rev = "290c76194890faa629de57a29e17a2dce95a9cbe";
    sha256 = "sha256-varLbi6rK6FJIVbnu2fba8IJX9TeQb2Dbc0l7uwhx/0=";
  };
  
  preConfigure = "find . -name '*.so' -delete; find . -name '*.o' -delete;";
  propagatedBuildInputs = [
    pkgs.rPackages.Rcpp
      pkgs.rPackages.foreach
      pkgs.rPackages.snow
      pkgs.rPackages.forecast
      pkgs.rPackages.ggplot2
      pkgs.rPackages.tseries
      pkgs.rPackages.randtoolbox
      misc
      ForecastComb
  ];
});
in
pkgs.rPackages.buildRPackage rec {
  name = "rArimaOption";
  version = "0.1.0";
  src = ./.;

  propagatedBuildInputs = with pkgs.rPackages; [
    forecast
  ] ++ [
    esgtoolkit
  ];

  nativeBuildInputs = with pkgs.rPackages; [
    knitr
    rmarkdown
    quarto
  ];

  doCheck = false;

  meta = with pkgs.lib; {
    description = "Option Pricing with ARIMA";
    license = licenses.mit;
  };
}
