# This file is auto-generated by R/setup/01_env/01_maintain_env.R
# Do not edit manually. Update DESCRIPTION instead.

library(esgtoolkit)
library(knitr)
library(rmarkdown)
library(forecast)
library(targets)
library(tarchetypes)
library(dplyr)
library(ggplot2)
library(ahead)
library(quarto)
