# R/setup/maintain_env.R
# This script reads DESCRIPTION, extracts dependencies, and generates packages.R and default.nix.

maintain_env <- function() {
  if (!requireNamespace("rix", quietly = TRUE)) {
    stop("rix package is not installed.")
  }
  library(rix)

  # 1. Read DESCRIPTION
  desc <- read.dcf("DESCRIPTION")
  
  get_packages <- function(field) {
    if (!(field %in% colnames(desc))) return(character(0))
    pkgs_str <- desc[1, field]
    if (is.na(pkgs_str)) return(character(0))
    pkgs <- strsplit(pkgs_str, ",")[[1]]
    pkgs <- trimws(pkgs)
    pkgs <- gsub("\\s*\\([^)]*\\)", "", pkgs)
    pkgs <- pkgs[pkgs != "R"]
    return(pkgs)
  }

  imports <- get_packages("Imports")
  suggests <- get_packages("Suggests")
  
  # Base dev tools that we always want in the shell
  dev_tools <- c("devtools", "usethis", "gert", "gh", "rix", "testthat", "roxygen2", "rcmdcheck")
  
  # Combine and dedup
  r_pkgs <- unique(c(imports, suggests, dev_tools))
  r_pkgs <- sort(r_pkgs)
  
  # 2. Write packages.R
  packages_r_content <- paste0(
    "# This file is automatically generated by R/setup/maintain_env.R\n",
    "# Do not edit this file directly.\n\n",
    "r_pkgs <- c(\\n  \"", paste(r_pkgs, collapse = "\",\n  \""), "\"\n)"
  )
  writeLines(packages_r_content, "packages.R")
  message("Generated packages.R")

  # 3. Generate default.nix
  # We use the shell_hook to set up the environment, specifically handling the $HOME issue.
  # Using R raw string r"---(...)---" preserves $HOME as is.
  # rix will write this into the nix file. 
  # We must ensure we don't double escape.

  shell_hook <- r"---(
mkdir -p $HOME/.config/positron
mkdir -p $HOME/.R/library
echo "R_LIBS_USER=$HOME/.R/library" >> $HOME/.Renviron

# Optional: Setup Positron/RStudio wrapper if needed (simplified from existing default.nix)
export R_MAKEVARS_USER=/dev/null
unset CI
printf "Environment loaded.\n"
)---"

  # System packages needed
  sys_pkgs <- c(
    "awscli2", "bc", "btop", "cacert", "clang", "curlMinimal", "direnv", "duckdb", 
    "gcc", "gh", "git", "glibcLocales", "gnupg", "htop", "jq", "less", 
    "nix", "nodejs", "pandoc", "quarto", "R", "tree", "which"
  )

  rix(
    r_ver = "4.4.2", # Use a fixed, recent R version
    r_pkgs = r_pkgs,
    system_pkgs = sys_pkgs,
    git_pkgs = NULL, # Assuming ahead/esgtoolkit are in rstats-on-nix snapshot
    ide = "none", # Use 'none' to avoid rix injecting strict rstudio/code wrappers
    project_path = ".",
    overwrite = TRUE,
    shell_hook = shell_hook
  )
  
  message("Generated default.nix")

  # 4. Generate package.nix (for Nix derivation builds)
  pkg_name <- desc[1, "Package"]
  
  # imports go to propagatedBuildInputs
  # suggests (for building vignettes/tests) go to nativeBuildInputs
  
  # Format list for nix
  nix_list <- function(pkgs) {
    if (length(pkgs) == 0) return("")
    paste(pkgs, collapse = "\n    ")
  }
  
  package_nix_content <- sprintf(
'{ pkgs ? import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-02-24.tar.gz") {} }:

pkgs.rPackages.buildRPackage {
  name = "%s";
  src = ./.;

  propagatedBuildInputs = with pkgs.rPackages; [
    %s
  ];

  nativeBuildInputs = with pkgs.rPackages; [
    %s
  ];
}
', 
    pkg_name, 
    nix_list(imports),
    nix_list(suggests)
  )
  
  writeLines(package_nix_content, "package.nix")
  message("Generated package.nix")
}

if (!interactive()) {
  maintain_env()
}
